name: Bug Report
description: Fehler melden
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Fehlerbeschreibung
      description: Was funktioniert nicht?
    validations:
      required: true

